in_channels = 32  # Node features dimensionality - currently learned in both models
hidden_channels = 256
out_channels = 64
heads = 2  # Number of attention heads - not used in model_gae
epochs = 1000
num_nodes = 3000
learning_rate = 0.01
supervised_loss_factor = 0
missing_edge_fraction = 0.2  # Test ratio
patience = 5  # If validation performance fails to improve after this many validation loop runs, conclude testing
validation_frequency = 5  # Perform a validation loop every this many epochs
edge_reconstruction_threshold = 0.8  # Construct an edge if the decoded probability is over the threshold
num_graphs = 1000  # The number of synthetic graphs to generate
print_loss_every_n_epochs = 100  # For monitoring purposes
